export const {
	VITE_REACT_APP_SUPABASE_URL : SUPABASE_URL,
	VITE_REACT_APP_SUPABASE_KEY : SUPABASE_KEY,
	// REACT_APP_GOOGLE_CLIENT_ID : GOOGLE_CLIENT_ID,
	// REACT_APP_API_URL : BASE_API_URL,
	// REACT_APP_URL : BASE_APP_URL,
	// REACT_APP_FEEDBACK_URL : FEEDBACK_URL,
	// REACT_APP_MAGICBELL_KEY : MAGICBELL_KEY
} = import.meta.env
